name: CouchDB
version: "1.0.0"
slug: couchdb
description: Apache CouchDB running inside Home Assistant
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ports:
  5984/tcp: 5984
host_network: false
map: []
options: {}
schema: {}
