name: CouchDB
version: "1.0.0"
slug: couchdb
description: Apache CouchDB in Home Assistant
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ports:
  5984/tcp: 5984
image: null
options:
  username: admin
  password: changeme
schema:
  username: str
  password: str
