name: CouchDB
version: "1.0.3"
slug: couchdb
description: Apache CouchDB inside Home Assistant
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ports:
  5984/tcp: 5984
host_network: false
options:
  username: admin
  password: changeme
schema:
  username: str
  password: str
